### ISSUE TITLE
Telegram - GetUpdates Failure

### ISSUE THREAD

**Issue by e-ivkov** [soramitsu/nakayoshi#7]
Seems like the Telegram API has changed and the bot library telegrambot4s was not yet updated.

Error listing:
```
2021-03-16 11:46:21,011 [ERROR] jp.co.soramitsu.nakayoshi.BotTg in bridge-akka.actor.default-dispatcher-5 - GetUpdates failed
org.json4s.package$MappingException: unknown error
    at org.json4s.Extraction$.extract(Extraction.scala:43)
    at org.json4s.ExtractableJsonAstNode.extract(ExtractableJsonAstNode.scala:21)
    at info.mukel.telegrambot4s.marshalling.JsonMarshallers.fromJson(JsonMarshallers.scala:59)
    at info.mukel.telegrambot4s.marshalling.JsonMarshallers.fromJson$(JsonMarshallers.scala:59)
    at info.mukel.telegrambot4s.marshalling.JsonMarshallers$.fromJson(JsonMarshallers.scala:96)
    at info.mukel.telegrambot4s.marshalling.AkkaHttpMarshalling$.$anonfun$camelCaseJsonUnmarshaller$1(AkkaHttpMarshalling.scala:16)
    at akka.http.scaladsl.util.FastFuture$.$anonfun$map$1(FastFuture.scala:23)
    at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
    at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45)
    at akka.http.scaladsl.util.FastFuture$.map$extension(FastFuture.scala:23)
    at akka.http.scaladsl.unmarshalling.Unmarshaller.$anonfun$map$3(Unmarshaller.scala:26)
    at akka.http.scaladsl.unmarshalling.Unmarshaller.$anonfun$transform$3(Unmarshaller.scala:23)
    at akka.http.scaladsl.unmarshalling.Unmarshaller$$anon$1.apply(Unmarshaller.scala:58)
    at akka.http.scaladsl.unmarshalling.Unmarshal.to(Unmarshal.scala:25)
    at info.mukel.telegrambot4s.clients.AkkaClient.toApiResponse(AkkaClient.scala:38)
    at info.mukel.telegrambot4s.clients.AkkaClient.$anonfun$apply$2(AkkaClient.scala:50)
    at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
    at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
    at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
    at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
    at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
    at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
    at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
    at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
    at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.reflect.InvocationTargetException: null
    at sun.reflect.GeneratedConstructorAccessor13.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.json4s.reflect.Executable.invoke(Executable.scala:52)
    at org.json4s.Extraction$ClassInstanceBuilder.instantiate(Extraction.scala:554)
    at org.json4s.Extraction$ClassInstanceBuilder.result(Extraction.scala:597)
    at org.json4s.Extraction$.$anonfun$extract$9(Extraction.scala:400)
    at org.json4s.Extraction$.customOrElse(Extraction.scala:606)
    at org.json4s.Extraction$.extract(Extraction.scala:392)
    at org.json4s.Extraction$CollectionBuilder.$anonfun$mkCollection$1(Extraction.scala:410)
    at scala.collection.immutable.List.map(List.scala:293)
    at org.json4s.Extraction$CollectionBuilder.mkCollection(Extraction.scala:410)
    at org.json4s.Extraction$CollectionBuilder.result(Extraction.scala:443)
    at org.json4s.Extraction$.$anonfun$extract$8(Extraction.scala:382)
    at org.json4s.Extraction$.customOrElse(Extraction.scala:606)
    at org.json4s.Extraction$.extract(Extraction.scala:382)
    at org.json4s.Extraction$.$anonfun$extract$6(Extraction.scala:366)
    at scala.Option.flatMap(Option.scala:271)
    at org.json4s.Extraction$.$anonfun$extract$5(Extraction.scala:366)
    at org.json4s.Extraction$.customOrElse(Extraction.scala:606)
    at org.json4s.Extraction$.extract(Extraction.scala:366)
    at org.json4s.Extraction$ClassInstanceBuilder.buildCtorArg(Extraction.scala:514)
    at org.json4s.Extraction$ClassInstanceBuilder.$anonfun$instantiate$4(Extraction.scala:546)
    at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:285)
    at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
    at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
    at scala.collection.TraversableLike.map(TraversableLike.scala:285)
    at scala.collection.TraversableLike.map$(TraversableLike.scala:278)
    at scala.collection.AbstractTraversable.map(Traversable.scala:108)
    at org.json4s.Extraction$ClassInstanceBuilder.instantiate(Extraction.scala:546)
    at org.json4s.Extraction$ClassInstanceBuilder.result(Extraction.scala:597)
    at org.json4s.Extraction$.$anonfun$extract$9(Extraction.scala:400)
    at org.json4s.Extraction$.customOrElse(Extraction.scala:606)
    at org.json4s.Extraction$.extract(Extraction.scala:392)
    at org.json4s.Extraction$.extract(Extraction.scala:39)
    ... 29 common frames omitted
Caused by: java.lang.IllegalArgumentException: requirement failed
    at scala.Predef$.require(Predef.scala:268)
    at info.mukel.telegrambot4s.models.Update.<init>(Update.scala:44)
    ... 65 common frames omitted
 ```

**Comment by e-ivkov** [comment]
The fix is in development in PR https://github.com/bot4s/telegram/pull/97
